DROP TABLE IF EXISTS PEDIDOS;
DROP TABLE IF EXISTS CLIENTES;
DROP TABLE IF EXISTS USUARIOS;

CREATE TABLE IF NOT EXISTS USUARIOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    perfil VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CLIENTES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    telefone VARCHAR(50),
    data_cadastro DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS PEDIDOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cliente_id INT NOT NULL,
    usuario_id INT,
    data_pedido DATE NOT NULL,
    valor_total DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES CLIENTES(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id) ON DELETE SET NULL
);

INSERT INTO USUARIOS (username, password_hash, perfil) VALUES
('admin@sgcp.com', '$2a$10$KQujes4LtNZ6h3qgAqeMCe/zlf5GhwXlW.UYk0fleZ1Qs.pSn6egS', 'ADMIN'); -- Senha: teste123